steps:
  # بناء Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ecole-chebbi:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ecole-chebbi:latest'
      - '.'
  
  # رفع image إلى Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ecole-chebbi:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ecole-chebbi:latest'
  
  # نشر على Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecole-chebbi'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecole-chebbi:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:europe-west1:ecole-chebbi-db'

images:
  - 'gcr.io/$PROJECT_ID/ecole-chebbi:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ecole-chebbi:latest'

timeout: 1200s
